#!/bin/bash


configfile=/etc/vfio-pci1.cfg

vfiobind() {
    dev="$1"
        vendor=$(cat /sys/bus/pci/devices/$dev/vendor)
        device=$(cat /sys/bus/pci/devices/$dev/device)
        if [ -e /sys/bus/pci/devices/$dev/driver ]; then
                echo $dev > /sys/bus/pci/devices/$dev/driver/unbind
        fi
        echo $vendor $device > /sys/bus/pci/drivers/vfio-pci/new_id

}

modprobe vfio-pci

cat $configfile | while read line;do
    echo $line | grep ^# >/dev/null 2>&1 && continue
        vfiobind $line
done

#-bios /usr/share/qemu/bios.bin -vga none \
#sudo qemu-system-x86_64 -enable-kvm -M q35 -m 8192 -cpu host \
#sudo qemu-system-x86_64 -enable-kvm -M q35 -m 20480 -cpu host,kvm=off \
#-usb -usbdevice host:046d:c06b -usbdevice host:04d9:2013 \

sudo qemu-system-x86_64 -enable-kvm -M q35 -m 8192 -cpu host,kvm=off \
-smp 4,sockets=1,cores=4,threads=1 \
-bios /usr/share/qemu/bios.bin \
-device ioh3420,bus=pcie.0,addr=1c.0,multifunction=on,port=1,chassis=1,id=root.1 \
-drive file=/storage/windows8.img,id=disk,format=raw,if=none -device ide-hd,bus=ide.0,drive=disk \
-drive file=/home/matt/windows81.iso,id=isocd,format=raw,if=none -device ide-cd,bus=ide.1,drive=isocd \
-device vfio-pci,host=01:00.0,bus=root.1,addr=00.0,multifunction=on,x-vga=on \
-device vfio-pci,host=01:00.1,bus=root.1,addr=00.1 \
-boot menu=on \
#-vnc :1

exit 0
