#!/bin/bash

# vfio-bind 0000:01:00.0 # Video
# vfio-bind 0000:01:00.1 # Video
# vfio-bind 0000:03:00.0 # Sound

qemu-system-x86_64 \
    -enable-kvm \
    -machine smm=off \
    -m 20480 \
    -cpu host,kvm=off \
    -smp cores=4,threads=2 \
    -pflash /usr/share/ovmf/ovmf_x64.bin \
    -device qxl \
    -drive file=/storage/windows8.img,id=disk,format=raw,if=none \
    -device ide-hd,bus=ide.0,drive=disk \
    -drive file=/home/matt/windows81.iso,id=isocd,format=raw,if=none \
    -device ide-cd,bus=ide.1,drive=isocd \
    -usb \
    -vnc :0 \
    -boot menu=on

    #-usbdevice host:046d:0a1f \
    #-vga none \
    # -device vfio-pci,host=01:00.0,multifunction=on \
    # -device vfio-pci,host=01:00.1 \
    # -device vfio-pci,host=03:00.0 \
    #-device qxl \
