#!/bin/bash

vfio-bind 0000:01:00.0 # Video
vfio-bind 0000:01:00.1 # Video
vfio-bind 0000:03:00.0 # Sound

disable-right-display
qemu-system-x86_64 \
    -enable-kvm \
    -m 20480 \
    -cpu host,kvm=off \
    -smp cores=4,threads=2 \
    -pflash /usr/share/ovmf/ovmf_x64.bin \
    -device vfio-pci,host=01:00.0,multifunction=on \
    -device vfio-pci,host=01:00.1 \
    -device vfio-pci,host=03:00.0 \
    -drive file=/storage/windows8.img,id=disk,format=raw,if=none \
    -device ide-hd,bus=ide.0,drive=disk \
    -drive file=/home/matt/windows81.iso,id=isocd,format=raw,if=none \
    -device ide-cd,bus=ide.1,drive=isocd \
    -boot menu=on
    # -vnc :0 \
    #-serial stdio -device usb-mouse -device usb-kbd -show-cursor

    # -device qxl \
    # -vga xga \ 

    #-usb -usbdevice host:04d9:2013 -usbdevice host:046d:c06b \
    # Ethernet fix by going to windows device manager and reinstalling drivers
    #-machine smm=off \
    #     Das Brown Keyboard        Logitech Broken Mouse
    #-usb -usbdevice host:04d9:2013 -usbdevice host:046d:c06b \

    #-usbdevice host:046d:0a1f \
    #-vga none \
    #--enable-kvm -machine smm=off \
enable-right-display
